#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Plot results of a particle tracking experiment.
"""

# setup
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
import cmocean as cmo
import netCDF4 as nc
import numpy as np

from datetime import datetime, timedelta
import matplotlib.dates as mdates
import pandas
import matplotlib.transforms as mtrans
from matplotlib.colors import LogNorm
from mpl_toolkits.axes_grid1.inset_locator import inset_axes

def dar(ax):
    """
    Fixes the plot aspect ratio to be locally Cartesian.
    """
    yl = ax.get_ylim()
    yav = (yl[0] + yl[1])/2
    ax.set_aspect(1/np.sin(np.pi*yav/180))
    
# Build a code to plot BC's generated by code
#
# I want to compare it with the BC file generated for 2018
# with the LV3 files for 2018
    
plt.close('all')

rivfn = '/data0/ebrasseale/NADB2018/Input/river_tracer_4river_NADB2017_0.nc'

dsriv = nc.Dataset(rivfn)

rt = dsriv['river_time'][:]
rt_list = []
for t in rt:
    rt_list.append(datetime(1999,1,1)+timedelta(days=t))
    
rQ = dsriv['river_transport'][:]

nt,nriv = rQ.shape

fig,ax=plt.subplots(4,1,sharex=True,figsize=(8,10))

ax[0].plot(rt_list,rQ[:,:5])
ax[0].text(0.1,0.9,'Tijuana River Estuary',transform=ax[0].transAxes)
ax[0].set_ylabel('transport m3s-1')
ax[0].get_xaxis().set_visible("false")

for i in range(nriv-5):
    ax[i].plot(rt_list,rQ[:,5+i])
    ax[i].set_ylabel('transport m3s-1')
    ax[i].get_xaxis().set_visible("false")

ax[1].text(0.1,0.9,'Punta Bandera',transform=ax[1].transAxes)
ax[-1].get_xaxis().set_visible("true")
ax[-1].xaxis.set_major_formatter(mdates.DateFormatter("%b %d %Y"))
plt.setp( ax[-1].xaxis.get_majorticklabels(), rotation=30, ha="right",rotation_mode='anchor')
ax[-1].set_xlabel('Time')

dsriv.close()

plt.tight_layout()

out_fn = '/data0/ebrasseale/WQ_plots/ROMS_rivertransport_2018.png'
plt.savefig(out_fn)
